# Generated by Django 3.0.5 on 2020-04-29 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastry',
            options={'verbose_name_plural': 'Pastries'},
        ),
        migrations.RemoveField(
            model_name='pastry',
            name='pastry_author',
        ),
        migrations.RemoveField(
            model_name='pastry',
            name='pastry_name',
        ),
        migrations.RemoveField(
            model_name='pastry',
            name='pastry_slug',
        ),
        migrations.AddField(
            model_name='pastry',
            name='name',
            field=models.CharField(default='', max_length=240, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PastryIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ingredient')),
                ('pastry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pastry')),
            ],
            options={
                'verbose_name_plural': 'Pastry Ingredients',
            },
        ),
    ]
