# Generated by Django 3.0.5 on 2020-04-29 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200429_1757'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pastryingredient',
            unique_together={('ingredient', 'pastry')},
        ),
    ]
