# Generated by Django 3.0.5 on 2020-04-29 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200429_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastryingredient',
            options={},
        ),
        migrations.RemoveField(
            model_name='pastryingredient',
            name='amount',
        ),
        migrations.AddField(
            model_name='pastryingredient',
            name='gram',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
