# Generated by Django 3.0.5 on 2020-04-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200429_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.IntegerField(choices=[(0, '/kg'), (1, '/pc')], default=0),
        ),
    ]
