# Generated by Django 3.0.5 on 2020-05-01 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ingredient_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastryingredient',
            old_name='gram',
            new_name='unit',
        ),
    ]
