# Generated by Django 3.0.5 on 2020-05-03 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200503_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastry',
            name='name',
            field=models.CharField(max_length=240, unique=True, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
